### ISSUE TITLE
Display user's avatar on each post

### ISSUE THREAD

**Issue by huytd** [webuild-community/federated-blog#10]
Instead of show the host name of the post, we should show the user's avatar and name instead:

![image](https://user-images.githubusercontent.com/613943/123387241-6b569800-d54c-11eb-973f-92bd71568502.png)

This way, we can make it clear about the ownership of the post.

---

In order to do this, we need to make some enhancement on the RSS feed data we have, currently, it's just a plain list of feed URLs.

```
const FEEDS = [
  'https://thefullsnack.com/rss',
  'https://zerox-dg.github.io/blog/rss.xml',
  'https://quancam.net/rss',
  'https://learnlingo.co/feed/',
  ...
];
```

What I'm thinking about the new data structure would be:

```
const CHANNELS = [
  {
    feedUrl: 'https://thefullsnack.com/rss',
    displayName: 'HuyTD',
    avatarUrl: '...'
  }
]
```

**Comment by giangnh92** [comment]
🥰
