### ISSUE TITLE
Build a pagination component

### ISSUE THREAD

**Issue by huytd** [webuild-community/federated-blog#24]
![image](https://user-images.githubusercontent.com/613943/123468103-2b240380-d5a6-11eb-9278-6ec2240edc05.png)

It should show the list of the available pages as decribed in the mockup.

Click on the three dot in the middle of the pagination should open a popover textbox, with Go button as well.

If there is only 1 page available, do not show the Previous/Next button, and show the disabled button with number 1 only.

**Comment by lqt93** [comment]
I will take this issue!
