### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by xuanvan229** [webuild-community/federated-blog#3]
## Steps to Reproduce
1. Go to https://webuild-blog.vercel.app/
2. Scroll down to bottom
3. Click "Load More"

## Context (Environment)
- Mac OS BigSur
- Microsoft Edge Version 91.0.864.54 (Official build) (x86_64)

![Screen Shot 2021-06-25 at 00 38 05](https://user-images.githubusercontent.com/22408713/123308244-a1e0e280-d54d-11eb-9595-9892c6fc6a15.png)

**Comment by huytd** [comment]
Fixed by #9
