### ISSUE TITLE
List post by user

### ISSUE THREAD

**Issue by huytd** [webuild-community/federated-blog#42]
We should have the ability to click on the author's name or avatar to list all posts by this author.

**Comment by lqt93** [comment]
Good point. Can we make a profile page for author. When we click on the author's name, it will redirect to their profile page which contains author's info and list of their posts.

**Comment by huyng12** [comment]
Hm, how about just redirect to the author's blog?

**Comment by huytd** [comment]
We already have a way to go to author's blog by clicking the blog's url under the name

<img width="214" alt="image" src="https://user-images.githubusercontent.com/613943/123691391-6e7eac00-d80a-11eb-9884-321666398a2b.png">

Sometimes, users still want to see all posts from one author, and then jump to another author, it's better to do it with their name, since it still "unused".

As for the profile page, we don't have that much info to show about each author, but that'll be possible in future.
