### ISSUE TITLE
Should add border radius in focus state of input

### ISSUE THREAD

**Issue by huyng12** [webuild-community/federated-blog#65]
Default state of the input have border radius but the focus state not. The focus state should have border radius too.

<img width="485" alt="Screen Shot 2021-07-06 at 02 31 14" src="https://user-images.githubusercontent.com/66771508/124512458-9ff70900-de02-11eb-8070-bcba08c0f37c.png">

<img width="485" alt="Screen Shot 2021-07-06 at 02 34 16" src="https://user-images.githubusercontent.com/66771508/124512483-ad13f800-de02-11eb-9408-c7b9181a883d.png">

**Comment by thien-do** [comment]
yeah.. this is quite complicated.. you can find more information here https://github.com/moaijs/moai/issues/64

The TL;DR is that:
- We are using "outline" for the focus state, which I believe is better than border and shadow.
- Unfortunately, whether outline should respect border radius or not is undefined in the specs, so in Firefox it does, but in Webkit it doesn't
- Don't know a good way to fix this yet

**Comment by huyng12** [comment]
I see, I'd like to close this issue and back with a solution later. Thank you.
